#include <bits/stdc++.h>
using namespace std;

int solve(string S)
{
    long long Ssize = S.size();
    long long sum = 0;
    if (Ssize == 1)
    {
        int ss = S[0] - '0';
        cout << ss << endl;
        return 0;
    }

    for (long long bit = 0; bit < (1 << (Ssize - 1)); bit++)
    {
        string num = "";
        for (long long i = 0; i < Ssize; i++)
        //全体10桁だと, i→0 ~9箇所 Ssize-1と思ってしまっている。
        {
            num += S[i];
            //cout << Ssize << endl;
            /*if (i == 9)
            {
                cout << bitset<10>(bit) << endl;
                cout << bitset<10>(1 << i) << endl;
            }*/

            if (bit & (1 << i)) //0:nasi 1:+
            {
                if (i == 9)
                {
                    cout << num << endl;
                }
                sum += stoll(num);
                num = "";
            }
        }
        sum += stoll(num);
    }

    cout << sum << endl;
    return 0;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    string S;
    cin >> S;
    solve(S);
    return 0;
}
